#!/bin/bash
#
# Bootstrap script to set up project
#


RED=$(tput setaf 160)
RESET=$(tput sgr0)

function display() {
    echo "-----> [`date +"%Y-%m-%d-%H:%M:%S"`] [bootstrap] $1"
}

if [ ! `which pip` ]; then
    display "${RED}Please install pip to install requirements${RESET}"
    exit 1
fi

display "Installing requirements.txt"
pip install -r requirements.txt
display "Done bootstrapping"

exit 0

# vim: ft=sh:
